[package]
name = "aoc-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
dotenv = "0.15.0"
env_logger = "0.11.8"
log = "0.4.28"
good_lp = { version = "1.8", features = ["minilp"], default-features = false }
regex = "1.12.2"
